services:
  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketdata
    ports: ["5432:5432"]
    volumes:
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketdata"]
      interval: 5s
      timeout: 5s
      retries: 20

  store:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/marketdata
      ADMIN_DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/marketdata
      APP_PORT: 8081
      ADMIN_TOKEN: dev-token-change-in-production
    ports: ["8081:8081"]
    depends_on:
      db:
        condition: service_healthy
