[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "market-data-store"
version = "0.1.0"
description = "Persistence and CQRS-lite store for market data (ticks, bars, options, fundamentals)."
readme = "README.md"
requires-python = ">=3.11"
authors = [{name = "Matt"}]
dependencies = [
    "psycopg[binary]>=3.1",
    "sqlalchemy>=2.0",
    "alembic>=1.13",
    "pydantic>=2.7",
    "loguru>=0.7",
    "python-dotenv>=1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.2,<9",
    "ruff>=0.6,<1",
    "black>=24.8,<25",
    "mypy>=1.11,<2",
]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E","F","I","UP","B","ARG","C90"]
exclude = ["venv",".venv",".git","dist","build"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
warn_unused_ignores = true
disallow_untyped_defs = true
